jobs:
  checking-flake:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
      with:
        fetch-depth: 1
    - uses: DeterminateSystems/nix-installer-action@v17
    - name: Run nix flake check
      run: nix flake check --impure --all-systems --no-build
    timeout-minutes: 30
'on':
  pull_request:
    branches:
    - master
    - dev-qezta
  push:
    branches:
    - master
    - dev-qezta
    paths-ignore:
    - '**/*.md'
    - .github/**
  workflow_dispatch: {}
